### ISSUE TITLE
Improve `DesmosQuery` and `DesmosMsg` with serde tag

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos-contracts#21]
Currently the structure of `DesmosMsg` is like:

```rust
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub struct DesmosMsg {
    pub route: DesmosRoute,
    pub msg_data: DesmosMsgRoute,
}
```

It could be simplified with serde tag attribute, say:
```rust
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
#[serde(rename_all = "snake_case", tag = "route", content = "msg_data")]
pub enum DesmosMsg {
    Profiles(ProfilesMsg),
    Subspaces(SubspacesMsg),
}
```
To produce the json like:
```json
{
    "route": "subspace",
    "msg_data": {
        "create_subspace": {
            "name": "test",
            "description": "test",
            "......"
        }
    }
}
```

We can do the same way to `DesmosQuery` as well.
It will reduce some code related to `DesmosRoute`. What do you think? @bragaz 

### Note:

it will break the current wasm part of modules in the desmos chain since the json format is different from the current one.

Reference: https://serde.rs/enum-representations.html#adjacently-tagged

**Comment by dadamu** [comment]
BTW, I have created a branch for testing it.
https://github.com/desmos-labs/desmos-contracts/tree/paul/refactor-route

**Comment by bragaz** [comment]
Nice one! This rename feature from serde is very powerful! I guess we can make this change, but we need to add also some docs lines in the file to let others that are not familiar with serde to properly understand the signature (maybe you can put the reference you put in the note directly?).

**Comment by dadamu** [comment]
@bragaz Sure, will do it with a PR.
