### ISSUE TITLE
Add conditional compilation to desmos-std

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/desmos-contracts#24]
In order to optimise the usage of desmos-std by devs in their contract, we can add [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html) to its packages. Conditional compilation allows to build only the features that are needed in a specific context.   
For instance, if someone wants to write a contract which only use `subspaces` messages, it's useless for them to also include other modules. Including them all will result in:  
- an increased contract size;
- a higher deployment cost.

To solve these problems, conditional compilation come useful, we just need to:
1) Updated the `config.toml`:

```toml
...
[features]
profiles = []
subspaces = []
...
```

2) Update the code where needed, with macros for features:
```rust
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
#[serde(rename_all = "snake_case", tag = "route", content = "msg_data")]
pub enum DesmosMsg {
    #[cfg(feature = "profiles")]
    Profiles(ProfilesMsg),
    #[cfg(feature = "subspaces")]
    Subspaces(SubspacesMsg),
}
```

Note:
Special thanks to @manu0466 to bring this to my attention

@dadamu what do you think about this?

**Comment by dadamu** [comment]
I love this idea. Let's add it.
